pipeline {
    agent any
    environment {
        DOCKER_IMAGE = "shaangoswami/n8n-image"
        DOCKER_TAG = "v1"
        KUBE_NAMESPACE = "default"
    }
    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }
         stage('Deploy to Kubernetes') {
            steps {
                withKubeConfig([credentialsId: 'my-k8s-config']) {
                    sh """
                    echo "--- FORCING KUBECTL INSTALL ---"
                    # Download kubectl to the current folder
                    curl -LO "https://dl.k8s.io/release/v1.28.0/bin/linux/amd64/kubectl"
                    chmod +x ./kubectl
                    
                    echo "--- DEBUG: CHECKING KUBECTL ---"
                    ./kubectl version --client
                    
                    # --- FIND DEPLOYMENT FILE ---
                    DEPLOY_FILE=\$(find . -name "deployment.yaml" | head -n 1)
                    WORK_DIR=\$(dirname "\$DEPLOY_FILE")
                    
                    # --- UPDATE IMAGE ---
                    sed -i 's|image: .*|image: ${DOCKER_IMAGE}:${DOCKER_TAG}|g' "\$DEPLOY_FILE"
                    
                    # --- DEPLOY USING LOCAL ./kubectl ---
                    echo "Applying configuration..."
                    ./kubectl apply -f "\$WORK_DIR" -n ${KUBE_NAMESPACE}
                    
                    # --- RESTART ---
                    ./kubectl rollout restart deployment/n8n -n ${KUBE_NAMESPACE} || true
                    """
                }
            }
        }

            }
        }
    }
}
